Week6
MarcRaeder/CS50Kurs pull request #11
Opened 2022-08-25 07:32 UTC by MarcRaeder

2022-08-25 08:45 UTC, stefanluth commented
Could you add [typing](https://docs.python.org/3/library/typing.html)?

2022-08-25 08:52 UTC, stefanluth commented on week6/dna/dna.py
> +        matches[i] = (longest_match(sequence, i))
```suggestion
        matches[i] = longest_match(sequence, i)
```

2022-08-25 08:52 UTC, stefanluth commented on week6/dna/dna.py
> +def longest_match(sequence, subsequence):
```suggestion
def longest_match(sequence: list[str], subsequence: list[str]) -> str:
```

Not sure if these are the correct types but this is an example of how to use them

2022-08-25 11:28 UTC, matthiasdanne requested changes
Haven't reviewed credit & dna so far.

Rest looks good, i have requested minor changes. 👍

2022-08-25 11:28 UTC, matthiasdanne commented on week6/world-cup/tournament.py
> +            winners.append(teams[i + 1])
```suggestion
        first_team_won = simulate_game(teams[i], teams[i + 1])
        if first_team_won:
            winners.append(teams[i])
        else:
            winners.append(teams[i + 1])
```

2022-08-25 11:28 UTC, matthiasdanne commented on week6/world-cup/tournament.py
> +    return random.random() < probability
```suggestion
    probability = 1 / (1 + 10 ** ((rating2 - rating1) / 600))
    
    return random.random() < probability
```

2022-08-25 11:28 UTC, matthiasdanne commented on week6/sentimental-readability/readability.py
> +index = 0.0588 * (letters / words * 100) - 0.296 * \
`index` is a rather generic name, you should name the used index here. 
If a reviewer wants further information on how or why this index is calculated he/she has a term to google. (And can compare wether this implementation of the used index is correct.)

```suggestion
coleman_liau_index = 0.0588 * (letters / words * 100) - 0.296 * \
```

2022-08-25 11:28 UTC, matthiasdanne commented on week6/sentimental-mario-more/mario.py
> +    print(" " * (Height - i), "#" * (i + 1), " ", "#" * (i + 1))
Oneliners are cool, yeah.

It is however debatable wether a longer solution would increase readability. In this rather simple task i would say no.

2022-08-25 14:36 UTC, stefanluth requested changes
Use 

```python
if __name__ == "__main__":
    main()
```

in all files :)

2022-08-25 14:36 UTC, stefanluth commented on week6/dna/dna.py
> +    for i in database[0]:
```suggestion
    for subsequence in database[0]:
```

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-cash/cash.py
> +from shelve import DbfilenameShelf
What's this?

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-credit/credit.py
> +    print("INVALID")
Move to a `main()` function

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-credit/credit.py
> +lenght = 0
```suggestion
length = 0
```

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-credit/credit.py
> +        break
Add try/catch similar to `cash.py`

![Screenshot 2022-08-25 at 16 31 00](https://user-images.githubusercontent.com/80166473/186692929-66bf01ed-1273-49b3-874f-9f1755553ad8.png)

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-credit/credit.py
> +    for d in even_digits:
```suggestion
    checksum += sum(odd_digits)

    for d in even_digits:
```

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-credit/credit.py
> +    print("INVALID")
```suggestion
else:
    print("INVALID")
```

Redundant

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-mario-less/mario.py
> +        Height = int(input("Height: "))
```suggestion
        height = int(input("Height: "))
```

2022-08-25 14:36 UTC, stefanluth commented on week6/sentimental-mario-more/mario.py
> +        Height = int(input("Height: "))
```suggestion
        height = int(input("Height: "))
```

2022-08-25 14:36 UTC, stefanluth commented on week6/world-cup/tournament.py
> +    return teams[0]["team"]
Is the return type really `list`?

2022-08-25 14:38 UTC, stefanluth commented on week6/sentimental-credit/credit.py
> +def luhn_checksum(card:int) -> int:
```suggestion
def luhn_checksum(card: int) -> int:
```

2022-08-25 14:38 UTC, stefanluth commented on week6/world-cup/tournament.py
> +def simulate_round(teams:list[str]) -> list[str]:
```suggestion
def simulate_round(teams: list[str]) -> list[str]: 
```

2022-08-25 14:38 UTC, stefanluth commented on week6/world-cup/tournament.py
> +def simulate_tournament(teams:list) -> list:
```suggestion
def simulate_tournament(teams: list) -> list:
```

2022-08-26 08:25 UTC, stefanluth approved these changes
Nice

2022-08-26 13:16 UTC, matthiasdanne approved these changes
Cool. 👍

2022-08-26 13:44 UTC, merged