add scrabble. Week2 is in progress
MarcRaeder/CS50Kurs pull request #5
Opened 2022-08-08 11:55 UTC by MarcRaeder

2022-08-10 14:04 UTC, matthiasdanne requested changes
I've only reviewed scrabble so far.

- Add a valid PR description

2022-08-10 14:04 UTC, matthiasdanne commented on week2/scrabble/scrabble.c
> +
```suggestion
        
```

2022-08-10 14:04 UTC, matthiasdanne commented on week2/scrabble/scrabble.c
> +        }
Are two if - loops with basicalyl the same logic necessary?  You could rewrite your if loop, so it works regardless wether the letter is capital or not.

2022-08-10 14:19 UTC, DevBastiS requested changes

2022-08-10 14:19 UTC, DevBastiS commented on week2/caesar/caesar.c
> +        printf("Usage: ./caesar key\n");
```suggestion
        printf("Usage: ./caesar key\n");
        
```

2022-08-10 14:19 UTC, DevBastiS commented on week2/caesar/caesar.c
> +            printf("Usage: ./caesar key");
```suggestion
            printf("Usage: ./caesar key");
            
```

2022-08-10 14:19 UTC, DevBastiS commented on week2/readability/readability.c
> +}
```suggestion
}

```

2022-08-10 14:19 UTC, DevBastiS commented on week2/substitution/substitution.c
> +    printf("Usage: ./substitution key\n");
```suggestion
    printf("Usage: ./substitution key\n");
    
```

2022-08-10 14:19 UTC, DevBastiS commented on week2/substitution/substitution.c
> +      printf("only use letters\n");
```suggestion
      printf("only use letters\n");
      
```

2022-08-10 14:19 UTC, DevBastiS commented on week2/substitution/substitution.c
> +    printf("Key must contain 26 characters.\n");
```suggestion
    printf("Key must contain 26 characters.\n");
    
```

2022-08-10 14:19 UTC, DevBastiS commented on week2/substitution/substitution.c
> +        printf("use each letter only once\n");
```suggestion
        printf("use each letter only once\n");
        
```

2022-08-11 06:42 UTC, MKrips approved these changes

2022-08-11 06:42 UTC, MKrips commented on week2/substitution/substitution.c
> +      key[i] = key[i] - 32;
```suggestion
      key[i] = toupper(key[i]);
```
This would be a more readable variant

2022-08-11 07:28 UTC, matthiasdanne requested changes
Update the PR title.

- Scrabble ✅
- Readability ❌ Changes requested.
- Caesar 🚧
- Substitution 🚧

2022-08-11 07:28 UTC, matthiasdanne commented on week2/readability/readability.c
> +int sentences = 0;
```suggestion
```

 Initializing function variables as 'global' variables should be avoided due to possible side effects. I would expect this initialization inside the main function.

You even initialize them a second time in your main function, which makes this code obsolete.

2022-08-11 07:28 UTC, matthiasdanne commented on week2/readability/readability.c
> +int count_sentences(string text);
See above.

2022-08-11 07:28 UTC, matthiasdanne commented on week2/readability/readability.c
> +    float L = (float)letters / (float)words * 100;
```suggestion
    int sentences = count_sentences(text);
    
    printLettersWordsSentences(text);
    
    float L = (float)letters / (float)words * 100;
```

Improves readability.

2022-08-11 07:28 UTC, matthiasdanne commented on week2/readability/readability.c
> +#include <cs50.h>
Your readability solution is good. 👍

You could improve it further by reducing the amount of times you are iterating over the whole text. Right now you're iterating three times over the whole text, once in each function. You could wrap these functions with the for loop, like this:

```
for (int i = 0; i < strlen(s); i++) {
  string text = ...

  count letters(text, i)
  count words(text, i)
  count sentences(text, i)
}
```

You're passing the current index to each function alongside with the text.

2022-08-11 09:10 UTC, matthiasdanne requested changes
Just some newline issues, otherwise readability is good. ✅

2022-08-11 09:10 UTC, matthiasdanne commented on week2/readability/readability.c
> +
```suggestion
```

2022-08-11 09:10 UTC, matthiasdanne commented on week2/readability/readability.c
> +
```suggestion
```

2022-08-11 09:10 UTC, matthiasdanne commented on week2/readability/readability.c
> +int count_sentences(string text, int sentences, int i)
```suggestion
}

int count_sentences(string text, int sentences, int i)
```

2022-08-11 09:10 UTC, matthiasdanne commented on week2/readability/readability.c
> +
```suggestion
```

2022-08-15 06:24 UTC, DevBastiS requested changes

2022-08-15 06:24 UTC, DevBastiS commented on week2/substitution/substitution.c
> +    else
Missing braces here.

2022-08-15 06:49 UTC, DevBastiS approved these changes

2022-08-15 06:52 UTC, merged