add complete week3
MarcRaeder/CS50Kurs pull request #6
Opened 2022-08-15 06:56 UTC by MarcRaeder

add week3

2022-08-15 09:58 UTC, matthiasdanne requested changes

2022-08-15 09:58 UTC, matthiasdanne commented on week3/plurality/plurality.c
> +}
```suggestion
}

```

2022-08-15 09:58 UTC, matthiasdanne commented on week3/plurality/plurality.c
> +        if (strcmp(candidates[i].name, name) == 0)
Add speaking variable

2022-08-15 09:58 UTC, matthiasdanne commented on week3/runoff/runoff.c
> +}
```suggestion
}

```

2022-08-15 09:58 UTC, matthiasdanne commented on week3/runoff/runoff.c
> +void eliminate(int min);
Should be ordered alphabetically.

2022-08-15 09:58 UTC, matthiasdanne commented on week3/runoff/runoff.c
> +        if (candidates[i].votes > voter_count/2)
```suggestion
        if (candidates[i].votes > voter_count / 2)
```
Can be a speaking variable like `candidateHasAbsoluteMajorityOfVotes`

2022-08-15 09:58 UTC, matthiasdanne commented on week3/runoff/runoff.c
> +#include <cs50.h>
This works and looks good, overall. 👍

You should remove existing comments and add speaking variables where possible.

2022-08-15 11:09 UTC, matthiasdanne requested changes

2022-08-15 11:09 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +}
```suggestion
}

```

2022-08-15 11:09 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +void print_winner(void);
Sort alphabetically

2022-08-15 11:09 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +bool locked[MAX][MAX];
Move the variable initialization into one block.

2022-08-15 11:09 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +int main(int argc, string argv[])
I would expect the main function at the top of the file.

2022-08-15 11:09 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +    return;
```suggestion
    }
    
    return;
```

2022-08-15 11:09 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +    return;
```suggestion
    }
    
    return;
```

2022-08-15 11:09 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +#include <cs50.h>
Aside from minor code style, this looks very good. 

What happens if all votes are evenly distributed? (like below). I haven't found anything on a 'tie' case in the task description.

<img width="348" alt="Bildschirmfoto 2022-08-15 um 13 05 39" src="https://user-images.githubusercontent.com/69143712/184624575-95dca61f-d8d0-4f46-b28b-13f15ef30da6.png">

2022-08-16 14:04 UTC, stefanluth commented on week3/plurality/plurality.c
> +}
[EOF](https://de.wikipedia.org/wiki/End_of_File) hinzufuegen

2022-08-17 12:06 UTC, matthiasdanne approved these changes
All in all this is good. 👍

I have tested the programs and they're working as expected.

2022-08-17 12:06 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +    for (int i = 0; i < candidate_count; i++)
```suggestion
    }

    for (int i = 0; i < candidate_count; i++)
```

2022-08-17 12:53 UTC, stefanluth requested changes
Only reviewed code style. Try to keep using one naming convention like snake_case and add use variables for more complicated if-checks.

2022-08-17 12:53 UTC, stefanluth commented on week3/plurality/plurality.c
> +    for (int i = 0; i < candidate_count; i++)
```suggestion
    }

    for (int i = 0; i < candidate_count; i++)
```

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +candidate;
```suggestion
} candidate;
```

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +bool vote(int voter, int rank, string name);
Sort by types, then alphabetically.

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +    for (int i = 0; i < candidate_count; i++)
```suggestion
    }

    for (int i = 0; i < candidate_count; i++)
```

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +
```suggestion
```

2022-08-17 12:53 UTC, stefanluth commented on week3/tideman/tideman.c
> +bool vote(int rank, string name, int ranks[]);
s.o.

2022-08-17 12:53 UTC, stefanluth commented on week3/tideman/tideman.c
> +    return 0;
```suggestion
    print_winner();

    return 0;
```

2022-08-17 12:53 UTC, stefanluth commented on week3/plurality/plurality.c
> +        bool NameEqualName = strcmp(candidates[i].name, name) == 0;
```suggestion
        bool NameEqualName = strcmp(candidates[i].name, name) == 0;
```
[Snake case](https://en.wikipedia.org/wiki/Snake_case), maybe `canditate_exists`

2022-08-17 12:53 UTC, stefanluth commented on week3/plurality/plurality.c
> +        bool NameEqualName = strcmp(candidates[i].name, name) == 0;
In `runoff.c` etc as well.

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +        if (strcmp(candidates[i].name, name) == 0)
```suggestion
        bool variable = strcmp(candidates[i].name, name) == 0;
        if (variable)
```

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +        if (candidates[i].votes < min && candidates[i].eliminated == false)
```suggestion
        bool variable = candidates[i].votes < min && candidates[i].eliminated == false;
        if (variable) 
```

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +        if (!candidates[i].eliminated)
```suggestion
        if (!candidates[i].eliminated)
```

Sometimes you use `!eliminated` and other times `eliminated == false`. Choose one

2022-08-17 12:53 UTC, stefanluth commented on week3/runoff/runoff.c
> +    return false;
This always returns false, is this intended?

2022-08-17 12:53 UTC, stefanluth commented on week3/tideman/tideman.c
> +            if (preferences[i][j] != preferences[j][i])
```suggestion
            bool variable = preferences[i][j] != preferences[j][i];
            if (variable)
```

2022-08-17 12:53 UTC, stefanluth commented on week3/tideman/tideman.c
> +        int current_strenght = preferences[pairs[i].winner][pairs[i].loser] - preferences[pairs[i].loser][pairs[i].winner];
```suggestion
        int current_strength = preferences[pairs[i].winner][pairs[i].loser] - preferences[pairs[i].loser][pairs[i].winner];
```

2022-08-17 12:53 UTC, stefanluth commented on week3/tideman/tideman.c
> +            int temp_strenght = preferences[pairs[j].winner][pairs[j].loser] - preferences[pairs[j].loser][pairs[j].winner];
```suggestion
            int temp_strength = preferences[pairs[j].winner][pairs[j].loser] - preferences[pairs[j].loser][pairs[j].winner];
```

2022-08-17 12:53 UTC, stefanluth commented on week3/tideman/tideman.c
> +}
```suggestion
    }
    
    return;
}
```

2022-08-17 14:22 UTC, stefanluth requested changes

2022-08-17 14:22 UTC, stefanluth commented on week3/runoff/runoff.c
> +            if (candidates[preferences[i][j]].eliminated == false)
```suggestion
            if (!candidates[preferences[i][j]].eliminated)
```

2022-08-17 14:22 UTC, stefanluth commented on week3/runoff/runoff.c
> +        bool current_candidate_with_lowest_votes = candidates[i].votes < min && candidates[i].eliminated == false;
```suggestion
        bool current_candidate_with_lowest_votes = candidates[i].votes < min && !candidates[i].eliminated;
```

2022-08-17 14:22 UTC, stefanluth commented on week3/tideman/tideman.c
> +bool hasCycle(int winner, int loser);
snake case

2022-08-17 14:22 UTC, stefanluth commented on week3/tideman/tideman.c
> +            int temp_strenght = preferences[pairs[j].winner][pairs[j].loser] - preferences[pairs[j].loser][pairs[j].winner];
Typo

2022-08-17 14:22 UTC, stefanluth commented on week3/tideman/tideman.c
> +bool hasCycle(int winner, int loser)
snake case

2022-08-18 08:40 UTC, stefanluth approved these changes

2022-08-18 08:43 UTC, merged