Add Week4
MarcRaeder/CS50Kurs pull request #7
Opened 2022-08-17 12:07 UTC by MarcRaeder

Add Week4
- volume
- filter-less
- filter-more
-  recover

2022-08-18 14:13 UTC, matthiasdanne requested changes
- Isn't week3 already merged? 
- You should add a [.gitignore file](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) and add `.DS_Store` there. These files are generated by Mac OS and you don't want to check them in.

2022-08-18 14:13 UTC, matthiasdanne commented on week3/plurality/plurality.c
> +}
Add final newline.

2022-08-18 14:13 UTC, matthiasdanne commented on week3/runoff/runoff.c
> +}
Add final newline.

2022-08-18 14:13 UTC, matthiasdanne commented on week3/tideman/tideman.c
> +}
Add final newline.

2022-08-18 14:13 UTC, matthiasdanne commented on week4/filter-less/bmp.h
> +RGBTRIPLE;
Add final newline.

2022-08-19 06:12 UTC, DevBastiS requested changes

2022-08-19 06:12 UTC, DevBastiS commented on week3/plurality/plurality.c
> +#define MAX 9
```suggestion
#define MAX_CANDIDATES 9
```

2022-08-19 06:12 UTC, DevBastiS commented on week3/plurality/plurality.c
> +        if (strcmp(candidates[i].name, name) == 0)
Move to speaking variable.

2022-08-19 06:12 UTC, DevBastiS commented on week3/plurality/plurality.c
> +}
Missing EOF.

2022-08-19 06:12 UTC, DevBastiS commented on week3/runoff/runoff.c
> +    }
```suggestion
    }
    
```

2022-08-19 06:12 UTC, DevBastiS commented on week3/runoff/runoff.c
> +    // Keep holding runoffs until winner exists
Remove comments if possible ;)

2022-08-19 06:12 UTC, DevBastiS commented on week3/runoff/runoff.c
> +    }
```suggestion
    }
    
```

2022-08-19 06:12 UTC, DevBastiS commented on week3/runoff/runoff.c
> +        return false;
Wrong indent

2022-08-19 06:12 UTC, DevBastiS commented on week3/runoff/runoff.c
> +        if (strcmp(candidates[i].name, name) == 0)
Move to speaking variable.

2022-08-19 06:12 UTC, DevBastiS commented on week3/runoff/runoff.c
> +
```suggestion
```

2022-08-19 06:12 UTC, DevBastiS commented on week3/tideman/tideman.c
> +#define MAX 9
```suggestion
#define MAX_CANDIDATES 9
```

2022-08-19 06:12 UTC, DevBastiS commented on week3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-08-19 06:12 UTC, DevBastiS commented on week3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-08-19 06:12 UTC, DevBastiS commented on week3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-08-19 11:24 UTC, matthiasdanne requested changes

2022-08-19 11:24 UTC, matthiasdanne commented on week4/filter-less/helpers.c
> +        for (int i = 0; i < height; i++)
- You use the same variable inside a nested scope. This is called variable shadowing and should be avoided.
- Your `blur` function is rather long and has many for-loops. You could move some of your code to helper functions with meaningful names, to increase the understandability of your code.

2022-08-22 10:03 UTC, matthiasdanne requested changes
Overall these are good solutions. ✅

- You could split your logic into smaller functions, to increase readability.
- Add a hint that the sobel operator was used to calculate edges. (maybe add a function `applySobelOperator`)

2022-08-23 09:12 UTC, matthiasdanne requested changes

2022-08-23 09:12 UTC, matthiasdanne commented on week4/filter-more/helpers.c
> +
```suggestion
```

2022-08-23 09:12 UTC, matthiasdanne commented on week4/filter-more/helpers.c
> +    }
Couldn't you just call `copy_gets_image(height, width, image, temp)` here?

2022-08-23 09:51 UTC, matthiasdanne approved these changes

2022-08-23 09:51 UTC, matthiasdanne commented on week4/filter-less/helpers.c
> +        return;
```suggestion
    return;
```

2022-08-23 12:37 UTC, stefanluth requested changes
See Louisa's PR :D

2022-08-23 12:39 UTC, stefanluth commented on week4/filter-less/helpers.c
> +    }
```suggestion
        }
    }

```

2022-08-23 12:41 UTC, stefanluth commented on week4/recover/recover.c
> +        bool checkBytesIndicateStartOfJPEG = (buffer[0] == 0xff && buffer[1] == 0xd8 && buffer[2] == 0xff && (buffer[3] & 0xff) == 0xe0);
Keep variable names consistent. (snake_case)

2022-08-24 06:40 UTC, stefanluth requested changes
See [Louisa's PR](https://github.com/LouisaStrunk02/CS50Kurs/pull/9).

2022-08-24 07:17 UTC, stefanluth requested changes

2022-08-24 07:17 UTC, stefanluth commented on week4/filter-less/helpers.c
> +            float Blue = image[i][j].rgbtBlue;
```suggestion
            float red = image[i][j].rgbtRed;
            float green = image[i][j].rgbtGreen;
            float blue = image[i][j].rgbtBlue;
```

2022-08-24 07:17 UTC, stefanluth commented on week4/filter-less/helpers.c
> +}
Indentation is off.

2022-08-24 07:17 UTC, stefanluth commented on week4/filter-more/helpers.c
> +            float Blue = image[i][j].rgbtBlue;
Lowercase variables

2022-08-24 07:17 UTC, stefanluth commented on week4/filter-more/helpers.c
> +        return;
Indentation

2022-08-24 07:17 UTC, stefanluth commented on week4/filter-more/helpers.c
> +    }
Missing return

2022-08-24 07:17 UTC, stefanluth commented on week4/volume/volume.c
> +    fclose(output);
Missing return

2022-08-24 07:39 UTC, stefanluth commented on week4/filter-more/helpers.c
> +        return;
Indentation

2022-08-24 07:44 UTC, stefanluth approved these changes

2022-08-24 07:47 UTC, merged